feat: add TF to manage a sensor mig
corelight/terraform-gcp-sensor pull request #1
Opened 2024-05-08 21:11 UTC by retr0h

Initial terraform to deploy a Corelight machine image based Sensor into a Managed Instance Group (MIG) behind the internal load balancer.

2024-05-10 19:27 UTC, thathaneydude requested changes

2024-05-10 19:27 UTC, thathaneydude commented on modules/bastion/outputs.tf
Can you output the instance id here?

2024-05-10 19:27 UTC, thathaneydude commented on modules/sensor/instance.tf
> +  name         = "${var.name_prefix}-mig-template"
The entire name should be a variable so folks can configure it to their own internal naming standards. Same for all the resources really.

2024-05-10 19:27 UTC, thathaneydude commented on modules/sensor/instance.tf
> +  name               = "${var.name_prefix}-mig-manager"
Full name should be a variable

2024-05-10 19:27 UTC, thathaneydude commented on modules/sensor/instance.tf
> +  name   = "${var.name_prefix}-autoscale"
Same here.

2024-05-10 19:27 UTC, thathaneydude commented on modules/sensor/load_balancer.tf
> +  name               = "${var.name_prefix}-traffic-monitor-health-check"
Should be a variable

2024-05-10 19:27 UTC, thathaneydude commented on modules/sensor/load_balancer.tf
> +  name          = "${var.name_prefix}-sensor-health-check-rule"
Should be a variable

2024-05-10 19:27 UTC, thathaneydude commented on modules/sensor/load_balancer.tf
> +  name                  = "${var.name_prefix}-traffic-ilb-backend-service"
Should be a variable

2024-05-10 19:27 UTC, thathaneydude commented on modules/sensor/outputs.tf
This should output the ids of the resources deployed

2024-05-10 19:27 UTC, thathaneydude commented on modules/sensor/load_balancer.tf
> +  name                   = "${var.name_prefix}-traffic-forwarding-rule"
Should be a variable

2024-05-10 19:27 UTC, thathaneydude commented on modules/sensor/load_balancer.tf
> +  ip_protocol            = "TCP"
Should this be UDP?

2024-05-10 20:24 UTC, retr0h commented on modules/sensor/load_balancer.tf
> +  ip_protocol            = "TCP"
It's not in the training material.

2024-05-17 19:21 UTC, thathaneydude approved these changes

2024-05-17 19:22 UTC, merged